### ISSUE TITLE
Unitialized variables when parsing almost any file [svg2png]

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#646] opened 2021-07-22 15:33 UTC
```
<svg width="100" height="100">
<linearGradient height="BackgroundImage" spreadMethod="56.75206" stop-opacity="SourceGraphic" >
<polygon repeatCount="" xlink:show="-178%" x2="691" >
</polygon>
</linearGradient>
<pattern patternTransform="" a="" xlink:show="reflect" >
</pattern>
</svg>
```
shows this erors
```
../src/lib/sw_engine/tvgSwRenderer.cpp:346:15: runtime error: load of value 190, which is not a valid value for type 'bool'
../src/lib/sw_engine/tvgSwRenderer.cpp:375:15: runtime error: load of value 190, which is not a valid value for type 'bool'

```
https://github.com/Samsung/thorvg/blob/934a95777c3c56d1daec803389c3fdf341b8febc/src/lib/sw_engine/tvgSwRenderer.cpp#L346
https://github.com/Samsung/thorvg/blob/934a95777c3c56d1daec803389c3fdf341b8febc/src/lib/sw_engine/tvgSwRenderer.cpp#L375

**Comment by hermet** [comment] 2021-07-26 07:52
@qarmin Actually I couldn't reproduce that error, but I believe it's fixed by this: https://github.com/Samsung/thorvg/commit/57e086db64a25b08e37b480b3582bba6b08d60e7

**Closed** 2021-07-27 14:55 UTC
Labels: bug
